version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        container_name: trust.network.nginx

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: trust.network.app

    neo4j:
        image: neo4j:latest
        ports:
            - 7473:7473
            - 7474:7474
            - 7687:7687
        environment:
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_AUTH: neo4j/password
        volumes:
            - ./storage/neo4j/data:/data
            - ./storage/neo4j/logs:/logs
            - ./storage/neo4j/plugins:/plugins
        container_name: trust.network.neo4j